// src/social-share-button-qwik.tsx
import { component$, useVisibleTask$, useSignal, type QRL } from '@builder.io/qwik';

interface Props {
  url?: string;
  title?: string;
  description?: string;
  hashtags?: string[];
  via?: string;
  platforms?: string[];
  theme?: 'dark' | 'light';
  buttonText?: string;
  customClass?: string;
  buttonStyle?: 'default' | 'primary' | 'compact' | 'icon-only';
  modalPosition?: 'center' | 'top' | 'bottom';
  onShare?: QRL<(platform: string, url: string) => void>;
  onCopy?: QRL<(url: string) => void>;
}

export const SocialShareButton = component$<Props>((props) => {
  const containerRef = useSignal<HTMLDivElement>();


  useVisibleTask$(({ cleanup }) => {
    if (typeof window !== 'undefined' && (window as any).SocialShareButton && containerRef.value) {
      const shareButton = new (window as any).SocialShareButton({
        container: containerRef.value,
        url: props.url || window.location.href,
        title: props.title || document.title,
        description: props.description || '',
        hashtags: props.hashtags || [],
        via: props.via || '',
        platforms: props.platforms || ['whatsapp', 'facebook', 'twitter', 'linkedin', 'telegram', 'reddit', 'discord'],
        theme: props.theme || 'dark',
        buttonText: props.buttonText || 'Share',
        customClass: props.customClass || '',
        buttonStyle: props.buttonStyle || 'default',
        modalPosition: props.modalPosition || 'center',
        onShare: props.onShare,
        onCopy: props.onCopy,
      });


      cleanup(() => {
        if (shareButton && typeof shareButton.destroy === 'function') {
          shareButton.destroy();
        }
      });
    }
  });

  return <div ref={containerRef} class="qwik-social-share-wrapper"></div>;
});

// src/social-share-button-react.jsx
import { useEffect, useRef } from "react";

/**
 * SocialShareButton React Wrapper
 *
 * Provides a React functional component that wraps the core SocialShareButton 
 * vanilla JS library. Handles lifecycle, dynamic updates, and provides 
 * sensible defaults for all sharing options.
 */
export const SocialShareButton = ({
  url,
  title,
  description = "",
  hashtags = [],
  via = "",
  platforms = ["whatsapp", "facebook", "twitter", "linkedin", "telegram", "reddit", "pinterest", "discord"],
  theme = "dark",
  buttonText = "Share",
  customClass = "",
  onShare = null,
  onCopy = null,
  buttonStyle = "default",
  modalPosition = "center",

  // Analytics: library emits events but never collects data
  analytics = true,
  onAnalytics = null, // Event callback
  analyticsPlugins = [], // Event adapters (see social-share-analytics.js)
  componentId = null, // Instance identifier
  debug = false, // Log events to console during development
}) => {
  // DOM reference for the injection target
  const containerRef = useRef(null);

  // Reference to the vanilla JS class instance
  const shareButtonRef = useRef(null);

  // Resolve fallback values when props are not provided (client-side only)
  const currentUrl = url || (typeof window !== "undefined" ? window.location.href : "");
  const currentTitle = title || (typeof document !== "undefined" ? document.title : "");

  /**
   * Initialization Effect
   * 
   * Sets up the vanilla JS component once the React component mounts.
   * Includes a safe check for the global SocialShareButton class.
   */
  useEffect(() => {
    if (containerRef.current && !shareButtonRef.current) {
      if (typeof window !== "undefined" && window.SocialShareButton) {
        shareButtonRef.current = new window.SocialShareButton({
          container: containerRef.current,
          url: currentUrl,
          title: currentTitle,
          description,
          hashtags,
          via,
          platforms,
          theme,
          buttonText,
          customClass,
          onShare,
          onCopy,
          buttonStyle,
          modalPosition,
          analytics,
          onAnalytics,
          analyticsPlugins,
          componentId,
          debug,
        });
      }
    }

    return () => {
      if (shareButtonRef.current) {
        shareButtonRef.current.destroy();
        shareButtonRef.current = null;
      }
    };
  }, []);

  /**
   * Update Effect
   * 
   * Synchronizes React prop changes with the underlying vanilla JS instance 
   * without re-mounting the entire component.
   */

  useEffect(() => {
    if (shareButtonRef.current) {
      // Use the library's built-in update method
      shareButtonRef.current.updateOptions({
        url: currentUrl,
        title: currentTitle,
        description,
        hashtags,
        via,
        platforms,
        theme,
        buttonText,
        customClass,
        onShare,
        onCopy,
        buttonStyle,
        modalPosition,
        analytics,
        onAnalytics,
        analyticsPlugins,
        componentId,
        debug,
      });
    }
  }, [
    currentUrl,
    currentTitle,
    description,
    hashtags,
    via,
    platforms,
    theme,
    buttonText,
    customClass,
    onShare,
    onCopy,
    buttonStyle,
    modalPosition,
    analytics,
    onAnalytics,
    analyticsPlugins,
    componentId,
    debug,
  ]);
  // Provide the mount point for the vanilla JS logic
  return <div ref={containerRef}></div>;
};

export default SocialShareButton;
